# Generated by Django 4.2.20 on 2025-03-13 09:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("quotes", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="feequote",
            options={"ordering": ["-last_updated"]},
        ),
        migrations.AlterModelOptions(
            name="quotequerylog",
            options={"ordering": ["-timestamp"]},
        ),
        migrations.RenameIndex(
            model_name="feequote",
            new_name="quotes_feeq_provide_f424d4_idx",
            old_name="quotes_feeq_provide_57fb66_idx",
        ),
        migrations.RenameIndex(
            model_name="feequote",
            new_name="quotes_feeq_source__f8a381_idx",
            old_name="quotes_feeq_source__8b0b3d_idx",
        ),
        migrations.RenameIndex(
            model_name="feequote",
            new_name="quotes_feeq_provide_a4606e_idx",
            old_name="quotes_feeq_provide_fd2c09_idx",
        ),
        migrations.RenameIndex(
            model_name="feequote",
            new_name="quotes_feeq_last_up_894d0b_idx",
            old_name="quotes_feeq_last_up_86f071_idx",
        ),
        migrations.RenameIndex(
            model_name="quotequerylog",
            new_name="quotes_quot_source__86c7d7_idx",
            old_name="quotes_quot_source__c9da84_idx",
        ),
        migrations.RenameIndex(
            model_name="quotequerylog",
            new_name="quotes_quot_timesta_8530d7_idx",
            old_name="quotes_quot_timesta_0b9e63_idx",
        ),
    ]
