# Generated by Django 4.2.20 on 2025-03-13 09:39

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="APIKey",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("key", models.CharField(max_length=64, unique=True)),
                ("name", models.CharField(help_text="Name of client/partner", max_length=100)),
                (
                    "email",
                    models.EmailField(
                        blank=True, help_text="Contact email", max_length=254, null=True
                    ),
                ),
                (
                    "tier",
                    models.CharField(
                        choices=[
                            ("registered", "Registered"),
                            ("premium", "Premium"),
                            ("enterprise", "Enterprise"),
                        ],
                        default="registered",
                        help_text="Access tier that determines rate limits and feature access",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                (
                    "rate_limit",
                    models.IntegerField(default=300, help_text="Requests per minute allowed"),
                ),
                ("total_requests", models.BigIntegerField(default=0)),
            ],
            options={
                "verbose_name": "API Key",
                "verbose_name_plural": "API Keys",
            },
        ),
        migrations.CreateModel(
            name="APIKeyUsageLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("endpoint", models.CharField(max_length=255)),
                ("http_method", models.CharField(max_length=10)),
                ("response_time_ms", models.IntegerField()),
                ("status_code", models.IntegerField()),
                ("ip_address", models.GenericIPAddressField()),
                ("user_agent", models.CharField(blank=True, max_length=255)),
                (
                    "api_key",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usage_logs",
                        to="remit_scout.apikey",
                    ),
                ),
            ],
            options={
                "verbose_name": "API Key Usage Log",
                "verbose_name_plural": "API Key Usage Logs",
                "indexes": [
                    models.Index(
                        fields=["api_key", "timestamp"], name="remit_scout_api_key_a358f7_idx"
                    ),
                    models.Index(fields=["endpoint"], name="remit_scout_endpoin_b11156_idx"),
                ],
            },
        ),
    ]
